"""Reuse successful local coding gates only against reconciled, identical inputs."""

import hashlib
import os
import shutil
import sys
import sysconfig
from pathlib import Path

from .coding import KINDS, baseline
from .coding_config import coding_options
from .execution import environment
from .gitops import git
from .models import Verification
from .storage import encode


def digest(value):
    return hashlib.sha256(encode(value).encode()).hexdigest()


class VerificationReceipts:
    def __init__(self, context):
        self.context = context
        self.runtime, self.store = context.runtime, context.runtime.store

    def environment_files(self, roots):
        """Reconcile dependency files too; equal interpreter paths alone are insufficient."""
        from .mutations import signature

        if not hasattr(self.runtime, "_verification_environment_files"):
            self.runtime._verification_environment_files = {}
        cache = self.runtime._verification_environment_files
        records, visited = {}, set()
        pending = [Path(root).resolve() for root in roots if Path(root).exists()]
        while pending:
            path = pending.pop()
            if path in visited:
                continue
            visited.add(path)
            if path.is_symlink():
                records[str(path)] = {"link": os.readlink(path)}
                pending.append(path.resolve())
            elif path.is_dir():
                # CPython checks source freshness; its generated bytecode does not
                # constitute a package version. Sourceless .pyc files are included.
                pending.extend(p for p in path.iterdir() if p.name != "__pycache__")
            elif path.is_file():
                stat = signature(path.stat())
                prior = cache.get(str(path))
                if prior and prior[0] == stat:
                    hashed = prior[1]
                else:
                    with path.open("rb") as stream:
                        hashed = hashlib.file_digest(stream, "sha256").hexdigest()
                    if stat != signature(path.stat()):
                        raise ValueError("Verification dependency changed during reconciliation")
                    cache[str(path)] = (stat, hashed)
                records[str(path)] = {"hash": hashed, "mode": stat[2]}
        return records

    def fingerprint(self):
        try:
            return self._fingerprint()
        except (OSError, ValueError, RuntimeError) as exc:
            # A changing/unreadable dependency disables reuse. In particular, a
            # post-gate reconciliation failure must not rerun a successful gate.
            self.store.event(
                self.context.session_id,
                "verification_receipt_invalidated",
                {
                    "reason": "Cannot establish a stable verification input fingerprint",
                    "error": str(exc),
                    "level": 3,
                },
                parent=self.context.source_event,
            )
            return None

    def _fingerprint(self):
        ctx, store = self.context, self.store
        config = store.config(ctx.session_id)
        # External judges, mutable containers and performance measurements are
        # not determined solely by the local repository. Their gates always run.
        if config.task.adapter != "coding" or config.execution.backend != "local":
            return None
        if coding_options(config.task).benchmark or coding_options(config.task).benchmark_commands:
            return None
        adapter = self.runtime.environment.adapter(ctx.session_id)
        adapter.mutations.reconcile(ctx, reason="before_verifier")
        root = Path(ctx.session.workspace.path).resolve()
        _, manifest = adapter.mutations.previous(str(root))
        env = environment(config.execution)
        original = baseline(ctx)
        executables = {}
        options = coding_options(config.task)
        commands_by_kind = {
            kind: getattr(options, field) or original["commands"].get(kind, [])
            for kind, field in KINDS.items()
        }
        # On system Python, base_prefix/lib is all of /usr/lib, including
        # unrelated toolchains. Reconcile Python's actual library directories.
        dependency_roots = {Path(__file__).parent}
        dependency_roots.update(
            Path(sysconfig.get_path(name))
            for name in ("stdlib", "platstdlib", "purelib", "platlib")
        )
        for variable in ("PYTHONPATH", "NODE_PATH"):
            dependency_roots.update(Path(p) for p in env.get(variable, "").split(os.pathsep) if p)
        if env.get("VIRTUAL_ENV"):
            dependency_roots.add(Path(env["VIRTUAL_ENV"]) / "lib")
        for commands in commands_by_kind.values():
            for command in commands:
                executable = shutil.which(command[0], path=env.get("PATH", os.defpath))
                if executable is None:
                    return None
                prefix = Path(executable).absolute().parent.parent
                if (prefix / "pyvenv.cfg").is_file():
                    dependency_roots.update({prefix / "lib", prefix / "pyvenv.cfg"})
                path = Path(executable).resolve()
                with path.open("rb") as stream:
                    executables[str(path)] = hashlib.file_digest(stream, "sha256").hexdigest()
        external_links = {}
        for name, row in manifest["files"].items():
            if row["value"]["kind"] == "symlink":
                target = (root / name).resolve()
                if not target.is_relative_to(root):
                    if not target.is_file():
                        return None  # Cannot establish a closed input set for outside directories.
                    with target.open("rb") as stream:
                        external_links[str(target)] = hashlib.file_digest(
                            stream, "sha256"
                        ).hexdigest()
        info = root.stat()
        inputs = {
            "workspace": [str(root), info.st_dev, info.st_ino],
            "git_directory": git(root, "rev-parse", "--absolute-git-dir").strip(),
            "head": manifest["head"],
            "files": {name: row["value"] for name, row in manifest["files"].items()},
            "external_links": external_links,
            "task": config.task.model_dump(mode="json"),
            "baseline": original,
            "execution": config.execution.model_dump(mode="json"),
            "environment": env,
            "executables": executables,
            "dependency_files": self.environment_files(dependency_roots),
            "runtime": [sys.version, sys.prefix],
        }
        # Do not persist environment values in receipts: only their fingerprint.
        return {"key": digest(inputs), "workspace": str(root), "inputs": inputs}

    def find(self, state):
        if state is None:
            return None
        ctx = self.context
        candidates = list(
            self.store.iter_events(
                ctx.session.root_id, tree=True, kind="verification_receipt_saved"
            )
        )
        for event in reversed(candidates):
            data = event["payload"]
            if data["key"] != state["key"]:
                continue
            try:
                result = Verification.model_validate(
                    self.runtime.artifacts.load(event["session_id"], data["artifact"])
                )
                if not result.passed:
                    continue
            except (OSError, ValueError, KeyError):
                continue  # Missing/corrupt receipts cannot authorize completion.
            self.store.event(
                ctx.session_id,
                "verification_receipt_reused",
                {
                    "key": state["key"],
                    "receipt_event": event["id"],
                    "artifact": data["artifact"],
                    "owner": event["session_id"],
                    "level": 3,
                },
                parent=ctx.source_event,
            )
            return result
        previous = next(
            (e for e in reversed(candidates) if e["payload"]["workspace"] == state["workspace"]),
            None,
        )
        if previous:
            self.store.event(
                ctx.session_id,
                "verification_receipt_invalidated",
                {
                    "receipt_event": previous["id"],
                    "reason": "Workspace, verification policy or environment identity changed",
                    "previous_key": previous["payload"]["key"],
                    "current_key": state["key"],
                },
                parent=ctx.source_event,
            )
        return None

    def save(self, before, result, artifact, source_event):
        if before is None or result is None or not result.passed:
            return
        after = self.fingerprint()
        if after is None:
            return
        # Tests may create caches, but any other change during the gate prevents
        # reuse against the resulting, unvalidated state.
        a, b = before["inputs"], after["inputs"]
        ignored = set(self.store.config(self.context.session_id).verification.generated_path_parts)

        def without_caches(inputs):
            return {
                **inputs,
                "files": {
                    name: value
                    for name, value in inputs["files"].items()
                    if not ignored.intersection(Path(name).parts)
                },
            }

        if without_caches(a) != without_caches(b):
            return
        self.store.event(
            self.context.session_id,
            "verification_receipt_saved",
            {
                "key": after["key"],
                "workspace": after["workspace"],
                "artifact": artifact,
                "verification_event": source_event,
                "level": 3,
            },
            parent=source_event,
        )
